version: '3.3'
services:
  db:
    image: mysql:8.0
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d:rw
      - ./mysql-data:/var/lib/mysql:rw
      - ./wait-for-mysql-started.sh:/wait-for-mysql-started.sh:ro
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: socialmediaapp
  minio:
    image: minio/minio
    command: server /data/minio
    volumes:
      - ./minio-data:/data/minio:rw
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: abcdef-123456789
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set socialmediaapp http://minio:9000 minioadmin abcdef-123456789;
      /usr/bin/mc mb --ignore-existing socialmediaapp/assets;
      /usr/bin/mc anonymous set public socialmediaapp/assets;
      exit 0
      "
  web:
    depends_on:
      - db
      - minio
      - createbuckets
    image: tomcat
    volumes:
      - ./server/SocialMediaBackend.war:/usr/local/tomcat/webapps/SocialMediaBackend.war:ro
    ports:
      - '8082:8080'

  nginx:
    depends_on:
      - web
      - minio
    image: nginx
    volumes:
      - ./nginx-config/:/etc/nginx/:ro
      - ./frontend:/usr/nginx/nhom-02-fe
    ports:
      - 80:80
