version: '3.3'
services:
  db:
    image: mysql:8.0
    healthcheck:
      test: mysql --protocol=socket -hlocalhost -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1'
      timeout: 10s
      retries: 100
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
    ports:
      - 9000:9000
    environment:
      MYSQL_ROOT_PASSWORD: 1234
  minio:
    image: minio/minio
    command: server /data/minio
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./minio-data:/data/minio:rw
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: abcdef-123456789
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set socialmediaapp http://minio:9000 minioadmin abcdef-123456789;
      /usr/bin/mc mb --ignore-existing socialmediaapp/assets;
      /usr/bin/mc anonymous set public socialmediaapp/assets;
      exit 0
      "
  web:
    depends_on:
      - db
      - minio
      - createbuckets
    image: tomcat
    volumes:
      - ./server/SocialMediaBackend.war:/usr/local/tomcat/webapps/SocialMediaBackend.war:ro
    ports:
      - '8082:8080'

