version: '3.3'
services:
  db:
    image: mysql:8.0
    volumes:
      - /opt/test:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
  minio:
    image: quay.io/minio/minio:RELEASE.2023-04-07T05-28-58Z
    command: server /data/minio
    volumes:
      - ./minio-data:/data/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: abcdef-123456789
  web:
      depends_on:
        - db
      image: tomcat
      volumes:
        - ./server/SocialMediaBackend.war:/usr/local/tomcat/webapps/SocialMediaBackend.war:ro
      ports:
        - '8082:8080'

