version: '3.3'
services:
  db:
    image: mysql:8.0
    volumes:
      - /opt/test:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
  web:
      depends_on:
        - db
      image: tomcat
      volumes:
        - ./server/SocialMediaBackend.war:/usr/local/tomcat/webapps/SocialMediaBackend.war:ro
      ports:
        - '8082:8080'

