version: '3.3'
services:
  db:
    image: mysql:8.0
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d:rw
      - ./mysql-data:/var/lib/mysql:rw
      - ./wait-for-mysql-started.sh:/wait-for-mysql-started.sh:ro
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: socialmediaapp
  minio:
    image: minio/minio
    command: server /data/minio
    volumes:
      - ./minio-data:/data/minio:rw
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: abcdef-123456789
      MINIO_BROWSER: "off"
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set socialmediaapp http://minio:9000 minioadmin abcdef-123456789;
      /usr/bin/mc mb --ignore-existing socialmediaapp/socialmediaapp;
      /usr/bin/mc anonymous set public socialmediaapp/socialmediaapp;
      exit 0
      "
  web:
    depends_on:
      - db
      - minio
      - createbuckets
    image: tomcat:10
    ports:
      - "127.0.0.1:8082:8080"
    volumes:
      - ./deploy/be:/usr/local/tomcat/webapps:rw
    entrypoint: ["/usr/local/tomcat/bin/catalina.sh", "run"]